#!/bin/bash

  . $IPIC_HOME/scripts/ipicrun15x15meshGEMinp

  PPN=8
  NUM_PROCS=$(($XLEN*$YLEN))
  NUM_NODES=$((($NUM_PROCS-1)/$PPN+1))

  : create job script from template
  sed " \
    s#nodes=[0-9][0-9]*#nodes=$NUM_NODES# ;
    s#ppn=[0-9][0-9]*#ppn=$PPN# ;
    s#MSUB -e .*#MSUB -e $PWD/error.${XLEN}x${YLEN}txt# ;
    s#MSUB -o .*#MSUB -e $PWD/output.${XLEN}x${YLEN}.txt# ;
    s#XLEN=.*#XLEN=$XLEN#
    s#YLEN=.*#YLEN=$YLEN#
    s#NUM_PROCS=.*#NUM_PROCS=$NUM_PROCS#
  " $IPIC_HOME/env/judge/job.sh > job.sh
  echo Use:
  echo
  echo   vim job.sh GEM.inp
  echo
  echo to check that job script and input files are correct and then do:
  echo
  echo   msub job.sh
