#!/bin/bash

ME=${0##*/}
function usage()
{
  echo "
    $ME: prepare to run ipic3d job for supplied parameters
  
    usage: $ME <XLEN> <YLEN>
    
      <XLEN>: number of processors in X direction
      <YLEN>: number of processors in Y direction
  "
}

if [ $# -lt 2 ]; then usage; exit 1; fi

  . $IPIC_HOME/scripts/ipicrun15x15meshinp

  PPN=16
  NUM_PROCS=$(($XLEN*$YLEN))
  NUM_NODES=$((($NUM_PROCS-1)/$PPN+1))

  : create job script from template
  sed " \
    s@nodes=[0-9][0-9]*@nodes=$NUM_NODES@ ;
    s@ppn=[0-9][0-9]*@ppn=$PPN@ ;
    s@PBS -e .*@PBS -e $PWD/error.${XLEN}x${YLEN}txt@ ;
    s@PBS -o .*@PBS -e $PWD/output.${XLEN}x${YLEN}.txt@ ;
    s@XLEN=.*@XLEN=$XLEN@
    s@YLEN=.*@YLEN=$YLEN@
    s@NUM_PROCS=.*@NUM_PROCS=$NUM_PROCS@
  " $IPIC_HOME/env/deep/job.sh > job.sh
echo "
Use:

   vim job.sh data/parameters.inp

 to check that job script and input files are correct and then do:

   sbatch job.sh
"
