#!/bin/bash
  : Parallel mode needs data to be empty ; \
  rm -rf data/* ; \
  XLEN=$1 ; \
  YLEN=$2 ; \
  : calculate safe value of dt ; \
  if test $XLEN -gt $YLEN ; then MAX=$XLEN ; else MAX=$YLEN ; fi ; \
  dt_string=".5*4/$MAX" ; \
  dt=$(echo $dt_string|bc -l) ; \
  echo dt=$dt ; \
  : edit GEM.inp with modified parameters ; \
  sed " \
    s/^dt *=.*/dt = $dt/ ; \
    s/^XLEN *=.*/XLEN = $1/ ; \
    s/^YLEN *=.*/YLEN = $2/ ; \
    s/^nxc *=.*/nxc = $((15*$1))/ ; \
    s/^nyc *=.*/nyc = $((15*$2))/ ;" src/inputfiles/GEM.inp > GEM.inp ; \
  : print the command to be executed ; \
  echo "+ mpiexec -n $(($1*$2)) ./iPic3D GEM.inp | tee out.${1}x${2}.txt" ; \
  : execute the command ; \
  $IPIC_MPIRUN -n $(($1*$2)) ./iPic3D GEM.inp | tee out.${1}x${2}.txt
